name: Release API

on:
  push:
    branches:
      - "main"
    paths:
      - packages/api/**
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
            version: 7.0.0

      - name: Install
        run: pnpm install

      - name: Publish
        run: cd ./packages/api && pnpm run deploy
